### ISSUE TITLE
pagesを使用していないため、リロードするとページが無効になる

### ISSUE THREAD

**Issue by y-chan** [PGseatake/GenshinImpactDamageEmulatorV2#1]
こんにちは、v2 betaの開発お疲れ様です。

現状、各ページがcomponent化されており、RoutingはVue Routerで行われている形になっていて、コードとしては非常に管理しやすい形になっているかと思います。
しかし、RoutingをVue Routerで行っているせいで、静的サイトとしては適さない形(リロードするとページがお亡くなりになる)になっていると思います。

今後GitHub Pagesを離れ、SSR等でのデプロイをするのであれば問題ないかもしれません(Vue RouterがSSRだからといって効くのかは未検証)が、SSGとしては適しません。

そこで、2つ提案をさせて頂きたいです。
1. pagesを利用して、各ページを作り、Vue Routerを廃止する
2. indexページのみを使い、他のページはクエリ(`?p=chara`など)で管理する

なお、i18nを適用するにあたっても、どちらにせよVue RouterによるRoutingという選択肢は微妙だと思うので、変えなければならないと思っています。
個人的には1の案を推していきたいです(楽だと思うので)。

私の方でも少し実装し、余裕があればPRしてみようかと思います。

しかし、Vue Routerを使っている理由が他になにかあるのであれば、本PRは取り下げます。

**Comment by PGseatake** [comment]
（SPA・Code Splitting など、ほとんど理解していない状態で）
SPAにしつつ、Code Splittingする方法を検索しながら試したら、今のような構成になりました。

今のところ、SSRをする予定はないです。

現状より適切な構成があれば取り入れたいと思っているので、ご教示頂ければ幸いです。
（予備知識はほぼ0で開発始めてます...）

**Comment by y-chan** [comment]
Nuxtは、SPAまたはSSGを実行する場合`pages`下の全ての`.vue`ファイルに対してHTMLを生成します。
今回のアプリケーションは特にAPI等を用いないのと、v1は静的サイトだったこともあり、SPAではなくSSGによるサイトで良いと思っています(SSGにしても同じ挙動となるかは要確認)
よって、まずは[`pages`下のファイルを`components`下に移動するコミット](https://github.com/PGseatake/GenshinImpactDamageEmulatorV2/commit/1bee50c068abb1d3dc0ace374111afb45ab26340)と[Vue Routerを導入するコミット](https://github.com/PGseatake/GenshinImpactDamageEmulatorV2/commit/ec9a46a5e49e4e26953e2cfb8faeb51e5bd2df9a)をリバートしなければなりません。
例外的に`pages/_lang/index.vue`に関してはi18nも考慮して`pages/index.vue`に移動する必要があります。
まだ未検証ですが、私の感覚ではおそらくそれだけで十分だと思います。

加えてSSGにするためには`nuxt.config.ts`内の`ssr`オプションを削除し、デフォルト設定にすれば良さそうです。

**Comment by PGseatake** [comment]
vue-routerを廃止してSSG構成にしてみました！
一部 nuxt-i18n を導入していますが、正式対応は #2 で行います。

問題なさそうであれば、このままクローズしてください。
指摘あれば、ソースのリンクと共にこの issue にコメントください :bow:

**Comment by y-chan** [comment]
大丈夫そうです!
nuxt-i18n対応はほぼ完了と見てよさそうです(`localePath`の使用等々残ってはいますが)
あとi18nに関していえば
https://github.com/PGseatake/GenshinImpactDamageEmulatorV2/blob/19a6aee20bc1245865dcd737cf92e83f3e799ef3/nuxt.config.ts#L14-L16
これの消し忘れ対応だけで十分そうです。

対応お疲れ様です!
