### ISSUE TITLE
vue-i18nではなくnuxt-i18nの方が相性が良いと思われる

### ISSUE THREAD

**Issue by y-chan** [PGseatake/GenshinImpactDamageEmulatorV2#2]
現状、i18n化にはvue-i18nが用いられていると思います。
それもそれで良いと思いますが、せっかくNuxtを利用しているのであればnuxt用にカスタムされ、nuxt公式から公開されているnuxt-i18nの方を利用すべきと考えます。
こちらであれば、Routing等を自動で設定してくれる上に、細かい設定などをpluginフォルダ/ファイルを使わずとも、`nuxt.config.ts`内で設定できます。
また、TypeScript対応も万全であるため、使い勝手としては圧倒的だと思います。
vue-i18nとあまり使い勝手は変わらない上に高性能である(`localePath`関数などでi18nとしての使い勝手が向上している)ため、おすすめします。

問題なければこちらで実装してみようかと思います。

**Comment by PGseatake** [comment]
vue-i18nを使用しているのは、仕事でたまたまvue-i18nを使用していたので、そのまま使ってみました。
公式ページを少し覗いてみましたが、こちらの方が使いやすそうな感じはしました。
Routingとも絡むと思うので、 #1 が解決してから組み込んでみようと思います。

**Comment by PGseatake** [comment]
nuxt-i18n を使って多言語対応修正してみました。
ついでに、言語切り替えボタンも追加しています。
問題なければクローズをお願いします 🙇

**Comment by y-chan** [comment]
対応お疲れ様です!
